version: '2'

services:
  web:
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - 3000:3000
